### ISSUE TITLE
Secondaries Terminology Clarifications

### ISSUE THREAD

**Issue by wjwoodley** [tudo-astroparticlephysics/PROPOSAL#104]
What exactly is meant by the "secondaries"? What is `sec.energy`, and why does it start nearly at the primary particle energy and then continuously decrease?

It seems most of the information in `sec` is a copy of the information in `sec.particles` (for example, `sec.energy == [i.energy for i in sec.particles]` returns `True`). Is there information about the propagating particle stored anywhere?

And what is meant by parent particle? Is there a relationship between `sec.energy` and `sec.parent_particle_energy` (for example, `sec.energy[i] == sec.parent_particle_energy[i + 1]` returns `False`)?

**Comment by sudojan** [comment]
Hi,

the output is indeed unintuitive and has changed from version 5 to 6 as first restructuring arrangements were included in this release. (The rest of the restructuring is in the current branch `restructure_parametrization`)
The energy of the Secondary is the energy of the muon after a propagation step. This unintuitive Output is due to the restructuring of PROPOSAL for CORSIKA, where it serves as the propagator for the em interactions. Therefore the output has changed to a Track with the muon properties creating secondaries.
This unintuitive behavior will be corrected with the next big release when the `restructure_parametrization` branch is merged. Then one can decide to get either the energy losses or the muon track.

`sec.energy` is a shortcut for getting the energies at the interaction points (in C++ these are the `Query` methods). `sec.parent_particle_energy` is the shortcut for the particle energy before the interaction. The reason why `sec.energy[i]` doesn't equal `sec.parent_particle_energy[i+1]` are the continuous losses.

**Comment by sudojan** [comment]
This is improved in MR #137
