### ISSUE TITLE
Segmentation fault when propagating decay particles

### ISSUE THREAD

**Issue by daniel-zid** [tudo-astroparticlephysics/PROPOSAL#26]
I've had a strange error. In my Python code, I create a dictionary containing propagators. Using the propagators in this dictionary, I propagate either taus or antitaus. If one of the decay products is a muon, I pass the properties of this muon to the correspondent propagator and then propagate it to see if it creates particle showers. The weird thing is that this propagation randomly gives segmentation faults.

I can provide you with a simple code that reproduces this error.

**Comment by Jean1995** [comment]
I encountered similar problems when trying to create showers with PROPOSAL using python-bindings.

It is important to know that the return values of a propagator, the list of secondaries, are actually references to objects. These objects are managed by an instance of Output (which is shared by all propagators in your dictionary). Every time a new particle is propagated these objects are deleted so that the new list of secondaries can be saved. I believe that refering to a particle that has already been deleted could be causing the segfaults.

I was able to deal with this problem by directly storing all information from the secondaries that I need in python (before a new particle is propagated and therefore before the information is deleted).

**Comment by MaxNoe** [comment]
Shouldn't this be solved by always using shared pointers? pybind11 advertises that these "just work™"

**Comment by daniel-zid** [comment]
That makes sense. It seems that if I don't propagate while iterating the
array of secondary particles,
everything works. Thank you!

**Comment by sudojan** [comment]
This should now be fixed.
