### ISSUE TITLE
Negative rates causing Runtime Errors

### ISSUE THREAD

**Issue by Jean1995** [tudo-astroparticlephysics/PROPOSAL#273]
@pascalgutjahr tried to propagate 2e6 MeV muons in ice, using a `v_cut` of 0.001.
After some propagations, PROPOSAL threw the `no dNdx for this energy defined` runtime exception.

After some debugging, I learned that the problem is due to interpolation issues for the Ionization cross section. The dNdx interpolant looks like this:

![interpolant](https://user-images.githubusercontent.com/15159319/160567277-17820042-7b62-4f8f-adde-b58c9221ae65.png)

For E ≈ 170 MeV, the cross sections becomes negative due to overshooting. This is because the integrand becomes hard to interpolate for very small v, as for the 0.001 used in this case.

Our method which samples the stochastic loss, [`Interaction::SampleLoss`](https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/master/src/PROPOSAL/detail/PROPOSAL/propagation_utility/Interaction.cxx#L38), uses the sum of all rates to sample the interaction type, component and size of the loss. A negative rate therefore leads to wrong calculations here.

### Approach to solve this issue on branch [negative_rate_error](https://github.com/tudo-astroparticlephysics/PROPOSAL/compare/negative_rate_error)

The real problem here is the interpolation overshooting. However, we are probably unable to ensure that all interpolants for all possible combinations of EnergyCutSettings and media are going to perform correctly.

Therefore, to avoid these miscalculations, I am catching all negative rates calculated by the interpolant and set them to zero. This way, we "silently" ignore the interpolations problems and just ignore the corresponding interaction type.

However, for the case described above, this means that we are going to sample a bremsstrahlung interaction which should in reality be very unlikely:

![interpolant](https://user-images.githubusercontent.com/15159319/160570129-073132fb-31bc-4fb4-9bca-b7520e2ef8a1.png)

### Alternative approaches?

Alternatively, we could check for negative rates at some point (for example in [`Interaction::Rates`](https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/master/src/PROPOSAL/detail/PROPOSAL/propagation_utility/Interaction.cxx#L70)) and throw a warning (in addition to setting the rate to zero). We could also just throw a runtime error which stops the propagation.

If we show at least a warning, the user would see that something is wrong, probably with the interpolation. The user might want to change the InterpolationSettings to solve these issues.

If we even throw a runtime error, the problem is that PROPOSAL would be more likely to crash, even if the error only affects a negligible kinematic range (e.g. low muon energies as in the case described above). This way, we would _force_ the user to change their propagation or interpolation settings.

**Comment by sudojan** [comment]
A proposal for a long-term solution regarding those interpolation issues in general.

As you said, the real problem is the inaccurate interpolation, especially at the edges of the parameter space.
Although these areas are mostly tiny regions of the parameter space that get rarely sampled, they can also be the most interesting part of a simulation regarding the physics and be extremely relevant for analyses, e.g for searches of extremely stochastic muon events in tau or Glashow resonance searches. Therefore, I see this proposed alternative solution in setting the rates to zero (which was also done in the old PROPOSAL before the switch to the CubicInterpolation Library, if I remember correctly) more as a short-term solution. Especially, in the light of opportunities of importance sampling in PROPOSAL, which we discussed.

While the modular structure of PROPOSAL allows the user to adapt all relevant parameters, ranging from the number of interpolation points or the order of interpolation to the energy loss cuts, not every parameter should be adjusted manually by a user who just wants an accurate and stable propagation.

Since the default settings in PROPOSAL are well tested for the current users, mainly from neutrino astronomy, they might be different regarding muography. So, why does PROPOSAL not have an algorithm adjusting those parameters e.g. according to the given energy loss cuts, which checks during the creation of the interpolation tables, the degree of accuracy in the parameter space? Thereby, the adjustments would be optimized automatically and not manually.
